=== stephanheinemann/pairings/src/main/resources/xsd/pairings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright Â© 2024, Stephan Heinemann
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
        * Redistributions of source code must retain the above copyright
          notice, this list of conditions and the following disclaimer.
        * Redistributions in binary form must reproduce the above copyright
          notice, this list of conditions and the following disclaimer in the
          documentation and/or other materials provided with the distribution.
        * Neither the name of the <organization> nor the
          names of its contributors may be used to endorse or promote products
          derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd"
    xmlns:pairings="https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd"
    elementFormDefault="qualified">

    <element name="pairings">
        <complexType>
            <choice>
                <sequence>
                    <element name="pairing" type="pairings:Pairing" maxOccurs="unbounded" minOccurs="0"></element>
                </sequence>
                <sequence>
                    <element name="preliminaryPairing" type="pairings:PreliminaryPairing" maxOccurs="unbounded"
                        minOccurs="0"></element>
                </sequence>
                <sequence>
                    <element name="abbreviatedPairing" type="pairings:AbbreviatedPairing" maxOccurs="unbounded"
                        minOccurs="0"></element>
                </sequence>
            </choice>
            <attribute name="validFrom" type="date" use="required"></attribute>
            <attribute name="validTo" type="date" use="required"></attribute>
        </complexType>
    </element>

    <complexType name="Pairing">
        <complexContent>
            <extension base="pairings:PreliminaryPairing">
                <attribute name="trip" type="positiveInteger" use="required"></attribute>
                <attribute name="pairing" type="string" use="required"></attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PreliminaryPairing">
        <sequence>
            <element name="crew" type="pairings:Crew" minOccurs="1" maxOccurs="1"></element>
            <element name="initialDutyDays" type="pairings:InitialDutyDays" minOccurs="1" maxOccurs="1"></element>
            <element name="dutyDays" type="pairings:DutyDays" minOccurs="1" maxOccurs="1"></element>
        </sequence>
        <attribute name="base" type="pairings:Base" use="required"></attribute>
        <attribute name="pairingAnnotation" type="pairings:PairingAnnotation" use="required"></attribute>
        <attribute name="timeAwayFromBase" type="duration" use="required"></attribute>
        <attribute name="credit" type="duration" use="required"></attribute>
        <attribute name="creditAnnotation" type="pairings:CreditAnnotation" use="optional"></attribute>
        <attribute name="perDiem" type="float" use="required"></attribute>
        <attribute name="length" type="positiveInteger" use="required"></attribute>
    </complexType>

    <simpleType name="PairingAnnotation">
        <restriction base="string">
            <enumeration id="OT" value="OptimizedTrip"></enumeration>
            <enumeration id="OL" value="OptimizedLock"></enumeration>
            <enumeration id="MT" value="ManualTrip"></enumeration>
            <enumeration id="ML" value="ManualLock"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="CreditAnnotation">
        <restriction base="string">
            <enumeration id="M" value="MinimumValue"></enumeration>
            <enumeration id="L" value="LegValue"></enumeration>
            <enumeration id="D" value="DutyValue"></enumeration>
            <enumeration id="T" value="TripValue"></enumeration>
            <enumeration id="R" value="RatioValue"></enumeration><!-- Duty Day RIG 1:2 -->
        </restriction>
    </simpleType>

    <simpleType name="Base">
        <restriction base="string">
            <enumeration id="YEG" value="Edmonton"></enumeration>
            <enumeration id="YVR" value="Vancouver"></enumeration>
            <enumeration id="YWG" value="Winnipeg"></enumeration>
            <enumeration id="YYC" value="Calgary"></enumeration>
            <enumeration id="YYZ" value="Toronto"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="DutyAnnotation">
        <restriction base="string">
            <enumeration id="MO" value="MorningDuty"></enumeration>
            <enumeration id="RE" value="RedEyeDuty"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Aircraft">
        <restriction base="string">
            <enumeration id="_73W" value="Boeing 737-700 Winglets"></enumeration>
            <enumeration id="_73H" value="Boeing 737-800 Winglets"></enumeration>
            <enumeration id="_73G" value="Boeing 737-700"></enumeration>
            <enumeration id="_7M8" value="Boeing 737 MAX8"></enumeration>
            <enumeration id="_7S8" value="Boeing 737-800"></enumeration>
            <enumeration id="_7F8" value="Boeing 737-800 Freighter"></enumeration>
            <enumeration id="_789" value="Boeing 787-9"></enumeration>
            <enumeration id="DH4" value="Bombardier Q400"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Airline">
        <restriction base="string">
            <enumeration id="AA" value="American Airlines"></enumeration>
            <enumeration id="AC" value="Air Canada"></enumeration>
            <enumeration id="AM" value="Aeromexico"></enumeration>
            <enumeration id="DL" value="Delta Airlines"></enumeration>
            <enumeration id="EI" value="Aer Lingus"></enumeration>
            <enumeration id="FI" value="Icelandair"></enumeration>
            <enumeration id="HA" value="Hawaiian Airlines"></enumeration>
            <enumeration id="UA" value="United Airlines"></enumeration>
            <enumeration id="WS" value="WestJet Airlines"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Vehicle">
        <restriction base="string">
            <enumeration id="GND" value="Ground Transportation"></enumeration>
            <enumeration id="LIM" value="Limousine"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="Crew">
        <attribute name="captains" type="nonNegativeInteger" use="required"></attribute>
        <attribute name="firstOfficers" type="nonNegativeInteger" use="required"></attribute>
        <attribute name="flightAttendants" type="nonNegativeInteger" use="required"></attribute>
        <attribute name="extraFlightAttendants" type="nonNegativeInteger" use="required"></attribute>
    </complexType>

    <complexType name="InitialDutyDays">
        <sequence>
            <element name="initialDutyDay" type="pairings:InitialDutyDay" minOccurs="1" maxOccurs="31"></element>
        </sequence>
    </complexType>

    <complexType name="InitialDutyDay">
        <attribute name="date" type="date" use="required"></attribute>
        <attribute name="weekday" type="pairings:Weekday" use="required"></attribute>
    </complexType>

    <simpleType name="Weekday">
        <restriction base="string">
            <enumeration value="Monday"></enumeration>
            <enumeration value="Tuesday"></enumeration>
            <enumeration value="Wednesday"></enumeration>
            <enumeration value="Thursday"></enumeration>
            <enumeration value="Friday"></enumeration>
            <enumeration value="Saturday"></enumeration>
            <enumeration value="Sunday"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="DutyDays">
        <sequence>
            <element name="dutyDay" type="pairings:DutyDay" minOccurs="1" maxOccurs="5"></element>
        </sequence>
    </complexType>

    <complexType name="DutyDay">
        <sequence>
            <element name="checkin" type="pairings:Checkin" minOccurs="1" maxOccurs="1"></element>
            <element name="leg" type="pairings:Leg" minOccurs="1" maxOccurs="unbounded"></element>
            <element name="checkout" type="pairings:Checkout" minOccurs="1" maxOccurs="1"></element>
            <element name="layover" type="pairings:Layover" minOccurs="0" maxOccurs="1"></element>
        </sequence>
        <attribute name="sequence" type="positiveInteger" use="required"></attribute>
    </complexType>

    <complexType name="Leg" abstract="true">
        <attribute name="origin" type="string" use="required"></attribute>
        <attribute name="destination" type="string" use="required"></attribute>
        <attribute name="out" type="time" use="required"></attribute>
        <attribute name="in" type="time" use="required"></attribute>
        <attribute name="block" type="duration" use="required"></attribute>
        <attribute name="credit" type="duration" use="required"></attribute>
        <attribute name="creditAnnotation" type="pairings:CreditAnnotation" use="optional"></attribute>
        <attribute name="number" type="nonNegativeInteger" use="optional"></attribute>
    </complexType>

    <complexType name="GroundLeg">
        <complexContent>
            <extension base="pairings:Leg">
                <attribute name="vehicle" type="pairings:Vehicle" use="required"></attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="FlightLeg">
        <complexContent>
            <extension base="pairings:Leg">
                <sequence>
                    <element name="crew" type="pairings:Crew" minOccurs="0" maxOccurs="1"></element>
                </sequence>
                <attribute name="aircraft" type="pairings:Aircraft" use="optional"></attribute>
                <attribute name="airline" type="pairings:Airline" use="optional" default="WestJet Airlines"></attribute>
                <attribute name="operating" type="boolean" use="required"></attribute>
                <attribute name="timeOnGround" type="duration" use="optional"></attribute>
                <attribute name="tailSwap" type="boolean" use="optional" default="false"></attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Checkin">
        <attribute name="report" type="boolean" use="optional" default="false"></attribute>
        <attribute name="out" type="time" use="required"></attribute>
        <attribute name="timeOnGround" type="duration" use="required"></attribute>
        <attribute name="dutyAnnotation" type="pairings:DutyAnnotation" use="optional"></attribute>
    </complexType>

    <complexType name="Checkout">
        <attribute name="release" type="boolean" use="optional" default="false"></attribute>
        <attribute name="in" type="time" use="required"></attribute>
        <attribute name="block" type="duration" use="required"></attribute>
        <attribute name="timeOnGround" type="duration" use="required"></attribute>
        <attribute name="duty" type="duration" use="required"></attribute>
        <attribute name="credit" type="duration" use="required"></attribute>
        <attribute name="creditAnnotation" type="pairings:CreditAnnotation" use="optional"></attribute>
    </complexType>

    <complexType name="Layover">
        <sequence>
            <element name="accomodation" type="pairings:Accommodation" minOccurs="1" maxOccurs="1"></element>
            <element name="transportation" type="pairings:Transportation" minOccurs="1" maxOccurs="1"></element>
        </sequence>
        <attribute name="layover" type="duration" use="required"></attribute>
    </complexType>

    <complexType name="Accommodation">
        <attribute name="details" type="string" use="optional" default="TBD"></attribute>
        <attribute name="accomodation" type="duration" use="optional"></attribute>
    </complexType>

    <complexType name="Transportation">
        <attribute name="details" type="string" use="optional" default="TBD"></attribute>
        <attribute name="transportation" type="duration" use="optional"></attribute>
    </complexType>

    <complexType name="AbbreviatedPairing">
        <attribute name="pairing" type="string" use="optional"></attribute>
        <attribute name="days" type="string" use="required"></attribute>
        <attribute name="length" type="positiveInteger" use="required"></attribute>
        <attribute name="legs" type="string" use="required"></attribute>
        <attribute name="credit" type="duration" use="required"></attribute>
        <attribute name="creditRatio" type="duration" use="required"></attribute>
        <attribute name="perDiem" type="float" use="required"></attribute>
    </complexType>
</schema>

=== stephanheinemann/pairings/src/test/resources/xml/E3007.xml
<?xml version="1.0" encoding="UTF-8"?>
<pairings:pairings
    xmlns:pairings="https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/stephanheinemann/pairings/tree/master/src/main/resources/xsd ../../../main/resources/xsd/pairings.xsd "
    validFrom="2024-04-01" validTo="2024-04-30">
    <pairings:pairing timeAwayFromBase="PT5H28M" pairingAnnotation="OptimizedLock" perDiem="41.87"
        pairing="E007" base="Edmonton" trip="8" credit="PT4H" creditAnnotation="DutyValue">
        <pairings:crew captains="1" firstOfficers="1" extraFlightAttendants="0" flightAttendants="0" />
        <pairings:inidialDutyDays>
            <pairings:dutyDay date="2024-04-29" weekday="Monday" />
        </pairings:inidialDutyDays>
        <pairings:dutyDays>
            <pairings:dutyDay sequence="1">
                <pairings:duty>
                    <pairings:checkin out="06:55:00" timeOnGround="PT1H" report="true"
                        dutyAnnotation="MorningDuty" />
                    <pairings:leg in="08:42:00" destination="YYJ" origin="YEG" out="07:55:00"
                        block="PT1H47M" credit="PT1H47M" xsi:type="pairings:FlightLeg" operating="true"
                        airline="WestJet Airlines" number="413" timeOnGround="PT0H48M"
                        aircraft="Boeing 737-800 Winglets">
                        <pairings:crew captains="1" firstOfficers="1" extraFlightAttendants="1"
                            flightAttendants="3" />
                    </pairings:leg>
                    <pairings:leg in="12:08:00" destination="YEG" origin="YYJ" out="09:30:00"
                        block="PT1H38M" credit="PT1H38M" xsi:type="pairings:FlightLeg" number="416"
                        aircraft="Boeing 737-800 Winglets" operating="true" airline="WestJet Airlines">
                        <pairings:crew captains="1" firstOfficers="1" extraFlightAttendants="1"
                            flightAttendants="3" />
                    </pairings:leg>
                    <pairings:checkout in="12:23:00" duty="PT5H28M" timeOnGround="P15M"
                        block="PT3H25M" credit="PT4H" release="true" creditAnnotation="MinimumValue" />
                </pairings:duty>
            </pairings:dutyDay>
        </pairings:dutyDays>
    </pairings:pairing>
</pairings:pairings>
